// SPDX-FileCopyrightText: 2025-2026 Contributors to the Factory-X project
// SPDX-License-Identifier: Apache-2.0

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [

    {
      type: 'category',
      label: 'Methodik',
      link: {
        type: 'generated-index',
        title: 'Methodik der Hausbaulogik',
        description: 'Die Sektion erklärt die Methodik hinter der Hausbaulogik.',
        slug: '/methodology',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'methodology',
        },
      ],
    },
    {
      type: 'category',
      label: 'AI-Chatbot',
      link: {
        type: 'generated-index',
        title: 'AI-Chatbot',
        description: 'Diese Sektion erklärt, wie mithilfe eines AI-Chatbots die Hausbaulogik durchlaufen werden kann.',
        slug: '/ai',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'ai',
        },
      ],
    },
    {
      type: 'category',
      label: 'Workshop',
      link: {
        type: 'generated-index',
        title: 'Workshop-Konzept für die Hausbaulogik',
        description: 'Diese Sektion erklärt das Workshop-Konzept zur Anwendung der Hausbaulogik.',
        slug: '/workshop',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'workshop',
        },
      ],
    }
  ],
};

module.exports = sidebars;
